name = "Sutanto"
avatar = "images/me-twitter.jpg"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "Software Engineer"
company = 'Brader'
# company = '<a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>'
location = "Bogor"
# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.
[params]
  #layout = "compact"

[social]
  email = "sutanto.1010@gmail.com"
  # facebook = "yourfacebookusername"
  github = "sutanto1010"
  twitter = "sutanto1010"
